### ISSUE TITLE
Gerar GNRE DO DF

### ISSUE THREAD

**Issue by evandojunior** [nfephp-org/sped-gnre#10]
Sabem me informar se há uma propriedade para o campo *INSCRITO UF FAVORECIDA, na classe guia?

![captura de tela 2016-01-28 as 10 51 21](https://cloud.githubusercontent.com/assets/11771860/12644880/2ed40ae8-c5ad-11e5-9080-2a33c71720f5.png)

**Comment by marabesi** [comment]
Você tem que gerar a guia olhando a DOCUMENTAÇÂO oficial, não o emissor de guia fornecido pelo site
