### ISSUE TITLE
Duvida sobre o certificado

### ISSUE THREAD

**Issue by evandojunior** [nfephp-org/sped-gnre#12]
Com um único certificado é possível gerar as guias? ou para cada guia tem que ser o certificado do emitente?

**Comment by marabesi** [comment]
Você não gera "guias" e sim lotes, esses lotes por sua vez são limitados a 50 guias cada. Você pode emitir quantos lotes quiser com um único certificado.

**Comment by evandojunior** [comment]
Obrigado Matheus, ficou esclarecido agora.
