### ISSUE TITLE
Configuracao

### ISSUE THREAD

**Issue by evandojunior** [nfephp-org/sped-gnre#14]
Galera, seguinte...

Estou tentando rodar a API, porém até o momento sem sucesso, e encontrei algumas pessoas com duvidas também, aqui esta uma configuração de teste, estou usando um certificado emitido pela SERASA e ainda sim estou com problemas,  a resposta é sempre
error:14094412:SSL routines:SSL3_READ_BYTES:sslv3 alert bad certificate

Conseguem ver algo de errado?

<?php
require_once 'vendor/autoload.php';

class MySetup extends Sped\Gnre\Configuration\Setup {

```
public function getBaseUrl() {
    return 'http://localhost/';

}

public function getCertificateCnpj() {
    return '';

}

public function getCertificateDirectory() {
    return 'certs/QU4TRO.pfx';
}

public function getCertificateName() {
    return 'QU4TRO.pfx';

}

public function getCertificatePassword() {
    return 'minhaSenha';
}

public function getCertificatePemFile() {
    return 'certs/metadata/QU4TRO_certKEY.pem';

}

public function getEnvironment() {
    return '1';

}

public function getPrivateKey() {
    return 'certs/metadata/QU4TRO_privKEY.pem';

}

public function getProxyIp() {
    return NULL;

}

public function getProxyPass() {
    return NULL;
}

public function getProxyPort() {
    return NULL;
}

public function getProxyUser() {
    return NULL;
}
```

}

$minhaConfiguracao = new MySetup();

$guia = new Sped\Gnre\Sefaz\Guia();

$lote = new Sped\Gnre\Sefaz\Lote();

$lote->utilizarAmbienteDeTeste(true); // Descomente essa linha para utilizar o ambiente de testes

$lote->addGuia($guia);
$webService = new Sped\Gnre\Webservice\Connection($minhaConfiguracao, $lote->getHeaderSoap(), $lote->toXml());
echo $webService->doRequest($lote->soapAction());
?>

**Comment by marabesi** [comment]
Alguém já conseguiu se comunicar com sucesso na API ? @evandojunior aconselho que abra um tópico no grupo oficial do nfephp também para que outras pessoas consigam te ajudar.
