### ISSUE TITLE
Numero de Lote

### ISSUE THREAD

**Issue by evandojunior** [nfephp-org/sped-gnre#15]
Pessoal, alguem sabe alguma forma melhor para eu pegar o numero do lote que é retornado no envio para a sefaz, exemplo:
Essa é a string que é retornada, e eu preciso pegar apenas os numero que estão em negrito
1100Lote recebido com Sucesso**1605551179**2016-02-05 09:51:09200

Agradeço o apoio!

**Comment by primogf** [comment]
evandojunior,
como você resolveu o problema do ":SSL3_READ_BYTES:sslv3 alert bad
certificate" ?

2016-02-05 10:54 GMT-02:00 evandojunior notifications@github.com:
