### ISSUE TITLE
Incompatibilidade com sped-nfe

### ISSUE THREAD

**Issue by eduardoturconi** [nfephp-org/sped-gnre#19]
Ao instalar os pacotes no composer, algumas dependências são incompatíveis:

>   Problem 1
>     - Conclusion: remove zendframework/zend-barcode 2.3.9
>     - zendframework/zend-barcode 2.3.8 requires zendframework/zend-validator 2.3.8 -> satisfiable by zendframework/zend-validator[2.3.8].
>     - Conclusion: don't install zendframework/zend-validator 2.3.8
>     - zendframework/zend-barcode 2.3.7 requires zendframework/zend-validator 2.3.7 -> satisfiable by zendframework/zend-validator[2.3.7].
>     - Conclusion: don't install zendframework/zend-validator 2.3.7
>     - zendframework/zend-barcode 2.3.6 requires zendframework/zend-validator 2.3.6 -> satisfiable by zendframework/zend-validator[2.3.6].
>     - Conclusion: don't install zendframework/zend-validator 2.3.6
>     - zendframework/zend-barcode 2.3.5 requires zendframework/zend-validator 2.3.5 -> satisfiable by zendframework/zend-validator[2.3.5].
>     - Conclusion: don't install zendframework/zend-validator 2.3.5
>     - zendframework/zend-barcode 2.3.4 requires zendframework/zend-validator 2.3.4 -> satisfiable by zendframework/zend-validator[2.3.4].
>     - Conclusion: don't install zendframework/zend-validator 2.3.4
>     - zendframework/zend-barcode 2.3.3 requires zendframework/zend-validator 2.3.3 -> satisfiable by zendframework/zend-validator[2.3.3].
>     - Conclusion: don't install zendframework/zend-validator 2.3.3
>     - zendframework/zend-barcode 2.3.2 requires zendframework/zend-validator 2.3.2 -> satisfiable by zendframework/zend-validator[2.3.2].
>     - Conclusion: don't install zendframework/zend-validator 2.3.2
>     - zendframework/zend-barcode 2.3.1 requires zendframework/zend-validator 2.3.1 -> satisfiable by zendframework/zend-validator[2.3.1].
>     - Conclusion: don't install zendframework/zend-validator 2.3.1
>     - zendframework/zend-barcode 2.3.0 requires zendframework/zend-validator 2.3.0 -> satisfiable by zendframework/zend-validator[2.3.0].
>     - Conclusion: don't install zendframework/zend-validator 2.3.0
>     - Conclusion: don't install zendframework/zend-stdlib 3.0.1
>     - Installation request for nfephp-org/sped-nfe dev-master -> satisfiable by nfephp-org/sped-nfe[dev-master].
>     - Conclusion: don't install zendframework/zend-stdlib 2.3.9|install zendframework/zend-stdlib 3.0.1
>     - marabesi/gnre dev-master requires zendframework/zend-barcode 2.3._@dev -> satisfiable by zendframework/zend-barcode[2.3.9, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.3.5, 2.3.6, 2.3.7, 2.3.8].
>     - marabesi/gnre dev-master requires zendframework/zend-barcode 2.3._@dev -> satisfiable by zendframework/zend-barcode[2.3.9, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.3.5, 2.3.6, 2.3.7, 2.3.8].
>     - zendframework/zend-barcode 2.3.9 requires zendframework/zend-stdlib 2.3.9 -> satisfiable by zendframework/zend-stdlib[2.3.9].
>     - Conclusion: remove zendframework/zend-stdlib 2.3.9|install zendframework/zend-stdlib 3.0.1
>     - Installation request for marabesi/gnre dev-master -> satisfiable by marabesi/gnre[dev-master].

**Comment by marabesi** [comment]
Ja tivemos esse problema com o gerador do código de barras da sped-gnre

**Comment by marabesi** [comment]
2df364d

**Comment by robmachado** [comment]
Matheus;

Para sua informação, nas nova versões do sped-nfe, sped-cte, sped-mdfe, sped-da, sped-mail Não mais serão usadas as classes do zend. 
Para ver as dependências veja nos repositórios (atenção com as branchs  pois algumas dessas estruturas estão sendo fortemente refatoradas)
