### ISSUE TITLE
Extração de dados do certificado

### ISSUE THREAD

**Issue by marabesi** [nfephp-org/sped-gnre#29]
Recentemente tentei extrair os dados do certificado utilizando os métodos fornecidos pela SPED-GNRE e não obtive sucesso.

Apesar dos arquivos .pem serem gerados eles constam como "inválidos" na requisição ao webservice do governo.

Duas possíveis soluções:

1) Remover a parte de manipulação de certificados dessa API e utilizar o que a SPED-NFE possuí (O da NFE funciona perfeitamente)

2) Verificar o problema e ver em qual parte está o erro da extração dos dados

**Comment by robmachado** [comment]
Matheus veja a classe Certificate em sped-common já está estável e faz tudo que podemos necessitar aconcelho a usar

**Comment by marabesi** [comment]
@robmachado o @renandelmonico achou a solução usando exatamente a sped-common.

Para quem estiver enfrentando esse problema, dê uma olhada na explicação que o @renandelmonico da no grupo https://groups.google.com/d/msg/gnrephp/kbNWB3aEBbs/0g067FKlBgAJ
