### ISSUE TITLE
Problemas para renderizar o barcode

### ISSUE THREAD

**Issue by dbemfica** [nfephp-org/sped-gnre#3]
Bom dia

Estou usando o WAMP e usando os exemplos que tem no repositório, mas não está exibindo a código de barras da guia.

Também rodei o arquivo "gerar-codigo-de-barras.php" que está presente no exemplos mas também não mostra o código

Está tudo funcionando, ou que não estou fazendo algo de errado?

Desde já agradeço

**Comment by marabesi** [comment]
Pode ser alguma extensão sua faltando, se não me engano ela utiliza a lib GD para gerar o código de barras. Você pode checar isso ?

Att

**Comment by dbemfica** [comment]
Sim já verifiquei isso, o wamp tem um atalho para ativar essa extensão a onde ele ativa "extension=php_gd2.dll" mas ainda não resolveu

**Comment by llpereiras** [comment]
Diogo, bom dia!

Até 2 anos atraz quando utilizava windows + wamp, esse atalho não
funcionava, eu sempre precisei  alterar no arquivo php.ini dentro da pasta
do apache.

Procure por php_gd2 dentro do arquivo php.ini que fica dentro da pasta do
apache no diretorio onde foi realizado a instalação.

Este topico dá mais informações a respeito:
http://www.alvinpoh.com/how-to-activateinstall-gd-library-in-wamp-under-windows/

Abs,

Em ter, 5 de jan de 2016 às 09:06, Diogo Bemfica notifications@github.com
escreveu:

**Comment by dbemfica** [comment]
Isso eu já tinha tentado Leandro obrigado. Mas usei o XAMP e está tudo funcionando. então fica a minha dica para quem for usar o Windows,

**Comment by marabesi** [comment]
Bacana, era alguma coisa de configuração mesmo do WAMP
