### ISSUE TITLE
Verificar PSR-2 em todas as classes

### ISSUE THREAD

**Issue by marabesi** [nfephp-org/sped-gnre#31]
A APi segue um padrão razoável de estilo de código, mas seria bom unificar isso utilizando um padrão conhecido por todos.

A minha sugestão é usar o code sniffer configurado com a PSR-2 em todas as classes.

Após essa alteração irei adicionar a checagem no travis CI.

**Comment by robmachado** [comment]
É isso ai @marabesi esse tipo de padronização está sendo aplicado em todos os repositórios. :+1:
