### ISSUE TITLE
Atualização para o PHP7

### ISSUE THREAD

**Issue by marabesi** [nfephp-org/sped-gnre#33]
Vi que logo logo iremos ter o PHP 7.2 e com isso me veio a dúvida de migrar essa API para o formato do PHP7, atualizar com type hints e algumas outras funcionalidades.

Gostaria de saber a opinião de quem usa a API. Seria esse o próximo passo?

**Comment by renandelmonico** [comment]
Acredito que sim. Além disso alterar a geração de certificado e outra coisa que percebi é que o sped-gnre não está no packagist como um package do nfephp-org.

**Comment by marabesi** [comment]
@renandelmonico bom ponto sobre o packagist. Acho que o @robmachado consegue nos ajudar nisso, no meu entendimento o ideal seria ter somente nfephp-org/sped-gnre e não mais  marabesi/spend-gnre, certo?

**Comment by renandelmonico** [comment]
Isso, assim ficaria mais fácil até para os localizar no packagist. No meu ponto de vista essas serias as mudanças mais importantes a se fazer no momento. Tirando as já citadas podemos estudar outras funcionalidades.

**Comment by robmachado** [comment]
Já disponibilizei como nfephp-org/sped-gnre, só temos de ver se o webhook atualiza automaticamente os pacotes no packagist

**Comment by marabesi** [comment]
@robmachado vou dar uma verificada aqui pra ver se rola

**Comment by marabesi** [comment]
4130878

**Comment by carusogabriel** [comment]
@marabesi Bora trabalhar primeiro nessa atualização pro PHP 7? Muitos problemas do #34 estão relacionados ao `PHP 5.6`, acredito ser mais fácil fazermos a migração pro 7 e junto atualizar os testes.

**Comment by renandelmonico** [comment]
Acredito também que seja necessário a atualização para o PHP 7. É possível melhorar alguns pontos e fazer novas funcionalidades também...
