### ISSUE TITLE
Erro de dependência

### ISSUE THREAD

**Issue by lucianojmf** [nfephp-org/sped-gnre#37]
Olá pessoal, tudo bem?
Estou tentando instalar via composer o package na versão 0.1.4.
Meu PHP é o 5.6, estou utilizando laravel 4.2. Ao atualizar o composer, o seguinte errro é lançado:

> nfephp-org/sped-gnre 0.1.4 requires satooshi/php-coveralls dev-master -> no matching package found

Porém, o package php-coveralls na versão dev-master não é instalado/encontrado com sucesso, mesmo manualmente incluindo a depedencia no composer. Ao trocar para uma versão específica, exemplo:
> satooshi/php-coveralls 2.0.0

O mesmo erro de instalação do php-gnre ocorre, uma vez que ele não encontra a dependência dev-master do outro pacote.

Como posso resolver esse erro de package?

**Comment by marabesi** [comment]
Opa @lucianojmf beleza?

Como você alterou a versão especifica do pacote satooshi/php-coveralls?

Estava vendo que ele só tem a versão v2.0.0 no packagist (https://packagist.org/packages/satooshi/php-coveralls)

**Comment by marabesi** [comment]
@lucianojmf algum update nessa thread?
