### ISSUE TITLE
Alguns pacotes de dependências estão abandonados ou obsoletos.

### ISSUE THREAD

**Issue by crmdesenvolvimentos** [nfephp-org/sped-gnre#44]
Abaixo relação dos pacotes.
- Package container-interop/container-interop is abandoned, you should avoid using it. Use psr/container instead.

- Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.

- Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.

- Package satooshi/php-coveralls is abandoned, you should avoid using it. Use php-coveralls/php-coveralls instead.

- Package zendframework/zend-barcode is abandoned, you should avoid using it. Use laminas/laminas-barcode instead.

- Package zendframework/zend-diactoros is abandoned, you should avoid using it. Use laminas/laminas-diactoros instead.

- Package zendframework/zend-servicemanager is abandoned, you should avoid using it. Use laminas/laminas-servicemanager instead.

- Package zendframework/zend-stdlib is abandoned, you should avoid using it. Use laminas/laminas-stdlib instead.

- Package zendframework/zend-validator is abandoned, you should avoid using it. Use laminas/laminas-validator instead.

**Comment by renandelmonico** [comment]
Na PR #40 eu atualizei o php-coveralls/php-coveralls. Podemos ver de atualizar as outras libs também. O que acha @marabesi ?

**Comment by marabesi** [comment]
só atualizei os pacotes para usarem o namespace laminas, o trabalho pesado mesmo foi feito pelo @renandelmonico, agora ficou apenas um warning que é de outra lib e não tem nada a ver com as libs declaradas no composer do projeto:

`Package container-interop/container-interop is abandoned, you should avoid using it. Use psr/container instead.`

**Comment by marabesi** [comment]
Vou fechar essa issue porque o warning `Package container-interop/container-interop is abandoned, you should avoid using it. Use psr/container instead.` vem do pacote do laminas `"laminas/laminas-barcode": "^2.3",` e pelo o que investiguei, precisa migrar parauma outra lib pro warning não aparecer, ou esperar que atualizem a lib do próprio laminas-barcode.

De momento, como não tem nenhum plano pra fazer a migração para outra lib vou encerrar essa thread.
