### ISSUE TITLE
Zend\ServiceManager

### ISSUE THREAD

**Issue by dbemfica** [nfephp-org/sped-gnre#5]
Ao tentar executar o arquivo "exemplo/gerar-pdf.php" está apresentando um erro no Zend\ServiceManager\Exception\ServiceNotFoundException

Acredito que a Zend/ServerManager tenha atualizado. porque sei que a alguns dias atrás estava tudo funcionando, depois que eu dei um update no composer que começou esse problema.

Gostaria de avisar e saber se tem algo que eu possa fazer?

Obs: Estou usando o XAMP numa maquina Windows

**Comment by marabesi** [comment]
Sabe qual a última versão do ServerManager? O que eu tentaria nesse caso é usar uma versão anterior no composer

**Comment by marabesi** [comment]
@dbemfica acabei de alterar o composer.json para corrigir o erro

**Comment by dbemfica** [comment]
Obrigado
