### ISSUE TITLE
"error:14094412:SSL routines:SSL3_READ_BYTES:sslv3 alert bad certificate" 

### ISSUE THREAD

**Issue by evandojunior** [nfephp-org/sped-gnre#6]
Boa tarde!
Mesmo após configurar certificado digital, aconteceu o seguinte erro:
"error:14094412:SSL routines:SSL3_READ_BYTES:sslv3 alert bad certificate" .
Já aconteceu esse erro com alguém ai? como resolvo?
Obrigado!

**Comment by marabesi** [comment]
Você não tem outro certificado para testar ?

são duas possibilidades:

1) Certificado não está permitido a emitir GNRE
2) O certificado está vencido (verifique a data de vencimento)

**Comment by evandojunior** [comment]
Solicitei a permissao no site do GNRE, vou aguardar a resposta e testar novamente.

Obrigado Matheus!

**Comment by evandojunior** [comment]
Outra duvida, na class de configuracao, a url tem que esta nesse formato mesmo?

public function getBaseUrl() {
		return 'http://localhost/sped-gnre-master/exemplos/gerarGuia.php';
	}

**Comment by primogf** [comment]
evandojunior,
você conseguiu solucionar esse problema do "bad certificate" ?
estou com o mesmo problema a algumas semanas

**Comment by dlimars** [comment]
Olá, sobre o problema relativo ao certificado digital, vc conseguiu resolver? pois estou passando pelo mesmo problema.

**Comment by marabesi** [comment]
Para vocês que não conseguiram resolver o problema, façam o seguinte teste:

1) extraia os dados do certificado com o seguinte comando :

```
 openssl pkcs12 -in certificado.pfx -nokeys -out cert.pem
```

O último parâmetro é o nome arquivo que iremos utilizar, agora adicione o seguinte na sua classe de configuração da API :

``` php
class MinhaConf extends Setup {
    public function getCertificatePemFile() {
        return '/caminho/completo/cert.pem';
    }
}
```

No método **getCertificatePemFile** o caminho completo dos dados extraídos deve ser informado.

Após esses passos tudo funcionar, provavelmente é algo na extração dos dados do certificado.

**Comment by jone22e** [comment]
Já tenho permissão pra fazer GNRE, pois com o ACBR funciona;
Certificado não está vencido.
Não consigo resolver: 
error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate

**Comment by jone22e** [comment]
XML gerado pela API também não está validando:

Layout do arquivo de lote inválido!
Causa do Erro: cvc-elt.1: Cannot find the declaration of element 'soap12:Envelope'.

**Comment by renandelmonico** [comment]
> Já tenho permissão pra fazer GNRE, pois com o ACBR funciona;
> Certificado não está vencido.
> Não consigo resolver:
> error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate

Você tentou os passos que estão [nesse link](https://github.com/nfephp-org/sped-gnre#aten%C3%A7%C3%A3o-2)?

**Comment by jone22e** [comment]
> > Já tenho permissão pra fazer GNRE, pois com o ACBR funciona;
> > Certificado não está vencido.
> > Não consigo resolver:
> > error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate
> 
> Você tentou os passos que estão [nesse link](https://github.com/nfephp-org/sped-gnre#aten%C3%A7%C3%A3o-2)?

Sim, mas não deu certo.

Tentei também executar esse comando:

openssl s_client -showcerts -prexit -connect www.gnre.pe.gov.br:443 > cadeia.pem -cacerts -nokeys

E e passar no CURLOPT_CAINFO

Um detalhe é que estou usando WAMP em WINDOWS 10, talvez isso cause alguma interferência. 

E se eu passar CURLOPT_SSLVERSION = 3 diz que openssl não foi compilado com SSL3

**Comment by jone22e** [comment]
Consegui fazer uma certa configuração que parou o erro. Mas não retorna nada. No debug:

Array ( [url] => https://www.testegnre.pe.gov.br/gnreWS/services/GnreLoteRecepcao [content_type] => [http_code] => 0 [header_size] => 0 [request_size] => 0 [filetime] => -1 [ssl_verify_result] => 1 [redirect_count] => 0 [total_time] => 0.067657 [namelookup_time] => 0.000465 [connect_time] => 0.067619 [pretransfer_time] => 0 [size_upload] => 0 [size_download] => 0 [speed_download] => 0 [speed_upload] => 0 [download_content_length] => -1 [upload_content_length] => -1 [starttransfer_time] => 0 [redirect_time] => 0 [redirect_url] => [primary_ip] => 200.238.83.74 [certinfo] => Array ( ) [primary_port] => 443 [local_ip] => 192.168.2.123 [local_port] => 64076 [http_version] => 0 [protocol] => 2 [ssl_verifyresult] => 0 [scheme] => HTTPS [appconnect_time_us] => 0 [connect_time_us] => 67619 [namelookup_time_us] => 465 [pretransfer_time_us] => 0 [redirect_time_us] => 0 [starttransfer_time_us] => 0 [total_time_us] => 67657 )

**Comment by jone22e** [comment]
Outro detalhe, essa função addCurlOption não funciona passar o CURLOPT_CAINFO:

` public function addCurlOption(array $option)
    {
        foreach ($option as $key => $value) {
            $this->curlOptions[$key] = $value;
        }
        return $this;
    }`

Se na classe original não existe CURLOPT_CAINFO, a função não vai adicionar, ela só substitui configurações.
