### ISSUE TITLE
Forbidden

### ISSUE THREAD

**Issue by MarcosGrzeca** [nfephp-org/sped-gnre#7]
Estou tentando conectar no site para gerar a GNRE e está retornando a seguinte mensagem de erro

**Forbidden**
You don't have permission to access /gnreWS/services/GnreLoteRecepcao on this server.
_IBM_HTTP_Server at www.gnre.pe.gov.br Port 443_

Estou utilizando o mesmo certificado para conectar com o Sefaz da NFe.

```
public function getCertificateName() {
    return "certificado.pfx";
}

public function getCertificateDirectory() {
        return "/var/www/html/testes/nfephpgnre/exemplos/";
}

public function getCertificatePemFile() {
    return "mycert.pem";  //Contém public e private key
}

public function getPrivateKey() {
    return "private.pem"; //Contém private key
}
```

Alguém conseguiu solucionar esse problema?
Obrigado

**Comment by robmachado** [comment]
Você se registrou para obter acesso ??
_Isso não é automático !!_ você tem que se registrar e pedir acesso.

Roberto

**Comment by marabesi** [comment]
Exato e me lembro que quando da esse erro **Forbidden** ocorre também quando os dados do certificado não são enviados. 

Certifique-se que os dados corretos estão na classe de configuração

**Comment by MarcosGrzeca** [comment]
Sim, me registrei através da opção "Solicitar Uso do WebService".
Quanto ao certificado, é necessário fazer algo além de retornar as funções da classe "MySetup"?
Lembrando que o certificado já foi extraído.

**Comment by marabesi** [comment]
Você extrai como esses dados ?

**Comment by MarcosGrzeca** [comment]
Utilizando a função openssl_pkcs12_read do PHP

**Comment by MarcosGrzeca** [comment]
**Contém public e private key**

```
public function getCertificatePemFile() {
    return "mycert.pem";  //Contém public e private key
}
```

**Contém a private key**

```
public function getPrivateKey() {
    return "private.pem"; //Contém private key
}
```

Suas chaves também estão dessa forma?
Obrigado

**Comment by marabesi** [comment]
Utilize o da API para que não haja problema https://github.com/nfephp-org/sped-gnre/wiki/3%29-Extraindo-os-dados-do-certificado-com-a-GNRE-PHP

**Comment by MarcosGrzeca** [comment]
Utilizei o método da API e os arquivos gerados foram os mesmos, porém no link https://github.com/nfephp-org/sped-gnre/wiki/4)-J%C3%A1-possuo-os-dados-extra%C3%ADdos-do-certificado,-o-que-fazer-%3F.
verifiquei que nas funções getPrivateKey e getCertificatePemFile é necessário informar o caminho completo.

Informei o caminho completo e o erro agora é "SSL peer cannot verify your certificate." Vou pesquisar esse erro, caso alguém já enfrentou a mesma situação, por favor, me avise.

Obrigado

**Comment by marabesi** [comment]
Você tem certeza que esse certificado está válido ? Já testou com outro certificado ?

**Comment by evandojunior** [comment]
Estou com o mesmo problema, mesmo após solicitar no site do GNRE

**Comment by MarcosGrzeca** [comment]
Boa tarde.

Sim, esse certificado é utilizado para comunicar com o Sefaz e emitir as notas fiscais.

**Comment by fincatto** [comment]
Boa tarde.
Estou tendo esse mesmo problema agora. Vocês conseguiram resolvê-lo?

**Comment by renandelmonico** [comment]
Boa tarde @fincatto.

Eles chegaram a liberar o acesso após sua solicitação de uso do webservice? Qual empresa fez a emissão do seu certificado?

**Comment by fincatto** [comment]
Olá @renandelmonico. Sim, eu tinha acesso e descobri que o problema está no
certificado. Tinha um certificado emitido pelos Correios e renovei ele
também pelos correios mas o novo passou a não funcionar com a gnre. Emissão
de notas e outros serviços ok! Tens ideia do que pode ter acontecido? Tanto
o velho quanto o novo foram gerados usando a cadeia rfb v4, não era pra ter
problema...
Em qua, 14 de jun de 2017 às 17:24, Renan Delmonico <
notifications@github.com> escreveu:

**Comment by fincatto** [comment]
Somente para registro, não consegui fazer funcionar o certificado gerado pelos Correios, embora o antigo também fosse. Tive que gerar com uma outra empresa para poder funcionar.

**Comment by renandelmonico** [comment]
Bom dia, @fincatto !

Você tentou conectar informando a cadeia de certificação como explicado nesse link https://groups.google.com/forum/#!msg/gnrephp/kbNWB3aEBbs/0g067FKlBgAJ ?

**Comment by fincatto** [comment]
Bom dia.
Tentei informando a cadeia sim. Porém, alguma coisa estava errada com o
certificado, ou o portal não reconhecia o meu certificado.
Com o antigo estava funcionando bem e, após gerar mais um novo certificado,
usando outra certificadora que não os Correios, tudo voltou a funcionar bem.
Achei bastante estranho porque ainda não consegui identificar com certeza
qual foi o problema...

**Comment by renandelmonico** [comment]
@fincatto  Certo, caso descubra o motivo de não reconhecer o certificado, informe por favor, pois há muita gente com problema nos certificados.

**Comment by Horley123** [comment]
Opa, alguém conseguiu resolver o problema ? se sim agradeço o compartilhamento da solução
