### ISSUE TITLE
Class getBaseURL

### ISSUE THREAD

**Issue by evandojunior** [nfephp-org/sped-gnre#8]
Nas Classe MinhaConfiguracao o getBaseUrl, tem que ser o caminho do projeto, igual o que esta abaixo:  
public function getBaseUrl() {
        return 'http://localhost/sped-gnre-master/exemplos/gerarGuia.php';
    }

Ou outro endereço?

Att.

**Comment by marabesi** [comment]
A base tem que ser a url que vc está usando, no exemplo é localhost mas o seu pode ser 

```
http://meusite.local
```

Depende de como você está utilizando virtualhosts e a estrutura do seu projeto

**Comment by evandojunior** [comment]
Beleza, no caso aqui tambem é localhost, preciso identificar o diretorio?
exemplo: http://localhost/sped-gnre-master ou só o localhost?

**Comment by marabesi** [comment]
Só a URL Base mesmo no caso http://localhost

**Comment by evandojunior** [comment]
Ok! Obrigado!
