### ISSUE TITLE
Estou com duvidas na emissao para ES

### ISSUE THREAD

**Issue by thgcosta** [nfephp-org/sped-gnre#86]
Não consegui pegar as conf do estado pois a uf ES tem um site proprio para emissao da Guia, gostaria de saber como é feito ou se é feito a emissao pela biblioteca atual?

**Comment by robmachado** [comment]
Não é feito !! ES e SP são webservices MUITO diferentes

**Comment by thgcosta** [comment]
Muito obrigado pela resposta
