### ISSUE TITLE
Ambiente Homologacao

### ISSUE THREAD

**Issue by evandojunior** [nfephp-org/sped-gnre#9]
Onde devo usar para enviar os dados para o ambiente de homologação?
Att.

**Comment by marabesi** [comment]
Até o momento não tem ainda a utilização do ambiente de homologação, pois ao gerar as guias GNRE elas não possuem nenhum valor até serem pagas

**Comment by evandojunior** [comment]
Ok, Obrigado.

**Comment by marabesi** [comment]
@evandojunior funcionalidade implementada para utilizar o ambiente de homologação (http://www.testegnre.pe.gov.br/)
